#pragma once

#ifndef	  __CAMERA_TYPES_H_
#define	  __CAMERA_TYPES_H_

enum class CAMERA_TYPES
{
	CAMERA_FIRST_PERSON,
	CAMERA_SECOND_PERSON,
	CAMERA_THIRD_PERSON,
	CAMERA_FOLLOW,
	CAMERA_OTHER
}
#endif /* __CAMERA_TYPES_H_ */